# Generated by Django 5.2.2 on 2025-06-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
